services:
  ruby:
    build : .
    #command : "sleep 365d &&"
    command : "bundle exec jekyll serve -l -o --host=0.0.0.0"
    volumes:
      - "./_posts:/app/_posts"
      - "./assests:/app/assests"
    ports:
      - "4000:4000"
      - "35729:35729"
